/**
 * Tamu Academy — Article Data
 *
 * Static data structure for all articles. Each article maps to a published episode.
 * Status values: 'published' | 'in-development'
 *
 * No article text, statistics, dates, or sources have been invented.
 * Content fields are left null/empty pending editorial approval.
 */

export const ARTICLES = [
  {
    slug: 'the-real-cost-of-always-achieving',
    title: 'The Real Cost of Always Achieving',
    subtitle: 'Why, for a generation raised on someone else\'s sacrifice, achievement can feel like a debt that never closes — and what it would mean to set it down.',
    category: 'Mind and Wellbeing',
    status: 'in-development',
    summary: 'Achievement can become emotionally exhausting when it is experienced not simply as personal fulfillment, but as repayment for family and community sacrifice. This essay examines that hidden ledger through immigrant and diaspora experience, Ubuntu, and the distinction between honoring a gift and repaying an unpayable debt.',
    cardSummary: 'An exploration of how constant pressure to perform can affect identity, wellbeing, relationships, and the way success is understood.',
    author: 'Tex Wambui',
    publisher: 'Tamu Academy',
    publicationDate: null,
    updatedDate: null,
    readingTime: 9,
    videoId: 'DM8-hCO78Os',
    videoTitle: 'The Real Cost of Always Achieving',
    sections: [
      {
        heading: 'The Story We Were Told',
        paragraphs: [
          'Think about the last significant thing you achieved. The degree. The offer. The milestone you told yourself would finally feel like arrival.',
          'Now be honest about what happened after. Perhaps there was a moment — an evening, a good night\'s sleep. And then the floor moved. The goalposts slid back. Before the achievement had even settled, a quiet voice was already asking: what\'s next?',
          'We have flattering words for people who live inside that voice. Driven. Ambitious. High-achieving. But there is another way to describe it, and it explains the hollowness in a way the flattering words never do. A great many of us are not chasing achievement at all. We are running from a debt we can never pay off.',
          'The dominant story about success is a story of ownership. You work hard. You earn it. You climb. And what you reach is yours — proof of your talent and your discipline. Pull yourself up, and the view from the top belongs to you.',
          'It is a powerful story precisely because it is partly true. Effort is real. Discipline is real. But it is also incomplete, and you can tell it is incomplete by watching the people who did everything it prescribed — who climbed exactly as instructed — and arrived at the summit feeling not triumphant but hollow, anxious, already behind.',
          'When the story you were handed does not match the life you are living, the story has usually left something out. The familiar explanations — hustle culture, social media, late capitalism — are not wrong. They are simply shallow. They explain the pressure. They do not explain the hollowness. To reach that, we have to name something the achievement story never mentions: who actually paid for you to be standing where you stand.',
        ],
        pullQuote: null,
      },
      {
        heading: 'The Hidden Ledger',
        paragraphs: [
          'For some people, achievement really is a personal project, built up from a stable floor they were handed. But for many of us — particularly the children of immigrants, the diaspora, anyone whose family crossed an ocean or a border so the next generation might have a chance — achievement was never personal. It was funded.',
          'Consider what that funding actually was. Someone left a country they loved. Someone left their language, their mother, their entire sense of home, and boarded a plane to a place where their credentials did not count and their accent made them smaller. Someone worked, for years and quietly, far below their capacity — cleaning the building, driving the cab, stocking the shelves — so that you could sit in a classroom and think about none of it.',
          'And there is a sentence that travels down through such families, sometimes spoken, more often not: we gave up everything for you. It is almost always said in love. But it lands like an invoice.',
          'Because now the achievement is no longer yours. It is a return on investment. Every exam, every promotion, is not "something I did" but a payment against an obligation you never signed but fully intend to honor. You do not get to simply succeed. You have to succeed enough — enough to justify the plane ticket, the cleaned offices, the years the people who raised you will never get back.',
          'That is not a trophy. It is a ledger. And once you see achievement as a ledger rather than a prize, the hollowness begins to make sense — because of everything a ledger like this contains, one feature governs all the others: it can never be marked paid.',
        ],
        pullQuote: null,
      },
      {
        heading: 'A Debt With No Number',
        paragraphs: [
          'Not all debts are the same. A financial debt is survivable precisely because it ends. There is a number. You reach it, you are even, the account closes.',
          'But this debt is not made of money. It is made of sacrifice, and sacrifice has no exchange rate. How many promotions equal one parent surrendering their homeland? What salary offsets the years someone spent cleaning offices instead of practicing the vocation they trained for? How much success is "enough" to balance a person handing you the years they will not get back?',
          'There is no figure, because there is no unit.',
          'This is the engine beneath the moving finish line. It is not that you are greedy or broken or addicted to achievement. It is that you are trying to settle an account with no closing balance. Every win is logged rather than cleared, and the ledger reopens each morning. Worse, the logic feeds itself: every new achievement raises the stakes of stopping — look how much has been invested, look how far you\'ve come — so you run faster while the debt simply watches you run.',
          'Which raises a question most people are moving too quickly to ask. Where did this come from? Not the sacrifice — the sacrifice is real, and it is love. The logic: the idea that what you achieve, you owe; that your life is a repayment. To answer it, we have to move from psychology into philosophy — and into some of the oldest and most beautiful thinking about who we owe, and why.',
        ],
        pullQuote: 'A debt with no number is a debt that can never be marked paid.',
      },
      {
        heading: 'Ubuntu, and the Cost of a Beautiful Idea',
        paragraphs: [
          'Across much of African thought runs an idea named most precisely in the Nguni Bantu word Ubuntu, usually rendered: I am because we are.',
          'Set it beside the sentence the modern world runs on — I think, therefore I am. A single mind, alone, proving its own existence. Ubuntu proposes nearly the opposite: you do not become a person in isolation. You become a person through other people. Your humanity is handed to you by your community and the people who poured into you. You are because they are.',
          'This is true, and it is a corrective to one of the loneliest fictions of modern life — that you are a self-made individual who owes no one anything. But every powerful idea casts a shadow, and the more beautiful the idea, the more important it is to know where its shadow falls.',
          'Follow the logic all the way down. If I am because we are, then who I am belongs, in part, to the we. My achievements are not only mine; they are the community\'s. In its best light, that is gratitude — you never forget who carried you. In its shadow, it means you are never quite off the hook. Your life is not fully yours to spend. Your worth becomes a kind of collective property. And rest stops being something you are permitted and begins to feel like something you are stealing.',
          'This is where the two threads meet. The sacrifice of the people who raised you, and a philosophy of the collective self, lock together. One says we gave up everything for you. The other says you exist because of us, and for us. Together, achievement becomes neither trophy nor even debt, but rent — paid continually for the right to belong.',
          'None of this makes Ubuntu the villain, and Western individualism is not the cure; individualism has its own disease, and it is an uglier one — isolation, every-person-for-themselves, people growing old and dying alone in a culture that told them they were self-made. The point is not that one framework is right and the other wrong. It is that even our most beautiful inheritances carry a cost, and you cannot keep the beauty while setting down the cost until you are willing to name the cost aloud.',
        ],
        pullQuote: null,
      },
      {
        heading: 'Honoring Is Not Repaying',
        paragraphs: [
          'There is no tidy remedy for this, and anyone offering a five-step morning routine is not taking it seriously. You cannot set a boundary against the way you were raised, and you would not want to sever yourself from people who loved you enough to give up their lives for you.',
          'But there is one distinction that, once seen, is difficult to unsee: the difference between honoring a sacrifice and repaying a debt.',
          'A debt is repaid. It is compelled, it is endless, and — as we have seen — this one has no closing balance, so repaying it will consume a whole life and still fall short. Honoring is different. Honoring is chosen. It is finite. And, strangely, it tends to be joyful rather than depleting.',
          'Consider what the people who sacrificed for you actually want. Picture them clearly. Does the person who cleaned those offices want a ledger — want you grinding yourself to dust, anxious and hollow, achieving endlessly to "pay them back"? Or do they want you to be well: to have the life they could not, which by definition is a life with rest in it, and joy in it, and enough peace to actually enjoy the thing they bought you?',
          'Here is the quiet truth underneath all of it. You were never handed a bill. You were handed a gift. The ledger — the I owe, I owe, I owe — is not something they charged you. It is something we add ourselves, out of love and guilt and the exact logic traced above. The sacrifice was real. The invoice is one we wrote.',
          'And a gift asks only one thing: that you receive it, and then live a life worth the giving. Living well is the repayment. Your joy honors the sacrifice more than your exhaustion ever could. A burnt-out, hollow life does not make the plane ticket worth it. A whole one does.',
          'Read Ubuntu again, generously, and it gives itself back. I am because we are — so your rest is also theirs, your joy is also theirs. Your wholeness is not a betrayal of the people who made you; it is what they were reaching for the entire time. You do not have to earn your place at the table. That was always the point. You already belong. You always did.',
          'That is the real heart of Ubuntu — not you owe the we, but you are held by the we. And you do not have to pay rent on being held.',
        ],
        pullQuote: 'You were never handed a bill. You were handed a gift.',
      },
      {
        heading: 'Put Down the Pen',
        paragraphs: [
          'Return, finally, to the hollow feeling — the one that arrives the moment after achievement, when the floor moves and the voice asks what\'s next before you have set down the trophy.',
          'It does not mean you are driven, or broken, or ungrateful. It is, more likely, your body quietly refusing to keep paying a debt that was never a debt — the part of you that knows no number was ever going to close this account, because it was never an account. It was love.',
          'We treat achievement as a debt we can never pay off. But the bill was never real. We wrote it ourselves, which means we can set down the pen. You do not owe anyone an unpayable debt for the gift of your own life. You only have to be brave enough to live it well.',
        ],
        pullQuote: 'Love does not want to be repaid. Love wants to be lived.',
        closingNote: 'This essay is part of Tamu Academy, an African-rooted learning platform exploring the mind, power, culture, public policy, economics, institutions, and the wider world. Watch the related episode through the [Tamu Academy Videos page](/videos).\n\nOn Ubuntu and Afrocentric thought, readers may look to Molefi Kete Asante\'s work on Afrocentricity and the broader literature on Nguni Bantu philosophy.',
      },
    ],
    keyTakeaways: [
      'Achievement pressure can be shaped by gratitude, guilt, family sacrifice, and inherited expectations — not only by personal ambition.',
      'When success is treated as repayment, achievement can begin to feel like an obligation with no clear closing balance.',
      'Honoring sacrifice does not have to mean endless performance; rest, joy, and living well can also honor what others made possible.',
    ],
    reflectionQuestions: [
      'When has achievement felt like something you owed rather than something you freely chose?',
      'Which expectations in your life come from family or community, and which reflect your own values and aspirations?',
      'What might honoring sacrifice look like if rest, wellbeing, and joy were also treated as meaningful outcomes?',
    ],
    editorialNote: 'This essay offers one reflective interpretation of achievement, family obligation, immigrant and diaspora experience, and Ubuntu. Experiences vary across families, communities, cultures, and philosophical traditions.',
    educationalNote: 'Tamu Academy content is provided for education and reflection. It is not a substitute for professional mental health care, diagnosis, or treatment.',
    relatedResources: [],
    sources: [],
    previousArticle: null,
    nextArticle: 'why-therapy-isnt-enough',
    seoTitle: 'The Real Cost of Always Achieving | Tamu Academy',
    seoDescription: 'Explore how family sacrifice, immigrant expectations, and Ubuntu can turn achievement into an unpayable debt — and how honoring differs from repayment.',
  },
  {
    slug: 'why-therapy-isnt-enough',
    title: 'Why Therapy Alone Isn\'t Enough',
    subtitle: 'Therapy is real, necessary, and often life-saving. But it was built primarily to support an individual — and for people whose pain is also communal, spiritual, and structural, healing the individual alone may not address the whole experience.',
    category: 'Mind, Systems and Wellbeing',
    status: 'in-development',
    summary: 'Therapy can provide essential professional support, language, tools, and confidential space. This essay considers why healing may also involve community, belonging, faith, family history, cultural meaning, and attention to structural conditions.',
    cardSummary: 'A look at why individual support matters, while social conditions, institutions, relationships, and community environments also shape wellbeing.',
    author: 'Tex Wambui',
    publisher: 'Tamu Academy',
    publicationDate: null,
    updatedDate: null,
    readingTime: 9,
    videoId: 'xLKNmgeX7m0',
    videoTitle: "Why Therapy Isn't Enough",
    safetyNote: 'A note before we begin: this is not an argument against therapy. Therapy can be valuable, necessary, and life-saving. If therapy is helping you, continue working with your provider. If you are considering professional support, a qualified mental-health professional can help you explore appropriate options. The argument here is not therapy or nothing — it is therapy, and what may also be needed alongside it.',
    sections: [
      {
        heading: null,
        paragraphs: [
          'Imagine someone who finally does it. After a lifetime of being taught that pain is private — that you pray about it, push it down, and do not air it out — they do the bravest thing they have ever done. They book the appointment.',
          'And it helps. Genuinely. For the first time, someone is listening. They acquire language for things that never had words.',
          'And yet, months in, sitting in that chair, some quiet part of them notices a gap. Something still unfinished. Something the room cannot quite reach.',
          'That gap is the subject of this essay. Not because therapy has failed them, and not because they have failed therapy — but because therapy may never have been built to reach the particular kind of pain many of us are actually carrying.',
        ],
        pullQuote: null,
      },
      {
        heading: 'The Door, and What Lies Beyond It',
        paragraphs: [
          'Most of us begin not in the chair but in silence.',
          'In a great many African homes — a great many immigrant homes, a great many homes full stop — we do not discuss that. Depression is not a condition but a weakness. Anxiety is not something to treat but something to pray away. And to admit you are struggling, when the people who raised you survived things you cannot imagine, can feel like a form of ingratitude: how dare you be sad in the life they all bled for?',
          'So the pain goes underground. We learn to perform fine. We call it strength. An entire generation grows up fluent in hiding.',
          'The conventional treatment of this subject stops precisely here. It says: the problem is stigma; break the stigma, go to therapy, the end. And that message matters — moving people through that door is genuinely important, and if the only thing this essay accomplishes is convincing one person that their pain is real and worth tending, it will have been worth writing.',
          'But stigma is the beginning of the conversation, not the end. Suppose you win that fight. You push past everything you were raised to believe. You walk through the door. Something happens on the other side of it that almost nobody discusses — and that, not the stigma, is what concerns us here.',
        ],
        pullQuote: null,
      },
      {
        heading: 'A Suit Cut for Someone Else\'s Body',
        paragraphs: [
          'You are in the chair. Why does it sometimes feel slightly foreign?',
          'Not wrong. Simply — like a beautifully made suit cut for someone else\'s body. Nothing is defective about the suit. It was measured for a different frame.',
          'Modern talk therapy emerged from a particular intellectual tradition carrying a particular assumption about what a person is. Western thought has, for several centuries, built almost everything atop a single premise: that the self is an individual — a separate, bounded unit. Healing, in that frame, happens privately: between one person and their own mind, in a room, behind a closed door.',
          'The model has real strengths, and this is not a dismissal of it. But notice the assumption underneath: that the fundamental unit of a human being is the lone individual, and that your problems live inside you.',
          'Now set that beside Ubuntu — "I am because we are." If I am because we are, then I am not a separate, bounded unit at all. I am a node in a web, made of the people around me. And if I am a node in a web, then perhaps my pain does not live only inside me either.',
          'Here, then, is the crux: therapy was designed to heal an individual, and many of us do not experience ourselves as only individuals. A healing model aimed at a self you do not fully recognize will sometimes feel as though it is reaching for someone who is not quite you. That is the gap in the chair. It is not your therapist failing, and it is not you resisting. It is a frame — a useful, valuable frame — built for a self that is only half of who you are.',
        ],
        pullQuote: null,
      },
      {
        heading: 'Three Kinds of Pain',
        paragraphs: [
          'If the self is not only individual, then suffering is not only individual either. Consider three kinds of pain that an "it is all inside you" model can quietly miss.',
          'The communal. A great deal of what we carry is entangled with other people. Family patterns. Things handed down. Wounds that occurred before you were born and somehow ended up living in your body. You can spend a year working on "your anxiety" and slowly realize the anxiety was passed to you three generations deep, by people who never had words for what they carried. Healing only the individual leaves the whole web untouched.',
          'The spiritual. For many of us, suffering is not solely a chemical event. It is read through faith, through meaning, through the question of what it is for. The question is not only what is the mechanism in my brain but where is God in this, and what is being asked of me. A purely clinical model can offer a very good answer to a question you are not only asking.',
          'The structural. This is the one we are most reluctant to say aloud. Some of the weight people carry is not coming from inside them at all. It comes from the world: the strain of migration, racism, poverty, being the only one in every room. These are real external forces, and they leave real marks on the mind and the body.',
          'There is a quiet risk in any model that treats all distress as something internal to be managed or reframed — it can end up handing you the bill for a wound the world inflicted. If you are exhausted from carrying something genuinely heavy, the answer cannot only be to change how you think about the weight.',
          'But this cuts both ways, and honesty requires saying so: this is not "it is all society\'s fault and you are powerless." That is its own trap, and it is equally immobilizing. There is what is inside you to tend, and there is what is outside you to name, and a whole picture holds both. Many therapists do precisely this work. The point is not that the profession is blind to it, but that the frame, left to itself, tilts inward — and for many of us, much of the story lies outward, in the web, and in the spirit.',
        ],
        pullQuote: 'The therapist\'s office and the village are not rivals; they are two halves of one whole.',
      },
      {
        heading: 'The Missing Half',
        paragraphs: [
          'If healing was made purely individual, then the missing half is everyone else.',
          'For most of human history, healing was not a solitary act behind a closed door. It occurred in community: elders, faith, ritual, story, the presence of people who carried the same history and required no explanation. You did not process your pain alone inside your own head. You were held through it.',
          'That is Ubuntu turned toward health. I am because we are — therefore I heal because we heal.',
          'Let me be as clear as possible, because this is where I am most likely to be misread: I am not proposing that anyone abandon therapy for the village. The therapist\'s office and the village are not rivals; they are two halves of one whole.',
          'Therapy provides what community often cannot: a trained, confidential, dedicated space; language; tools; a person whose entire task in that hour is you. Community provides what therapy often cannot: belonging, continuity, people who know your whole story, shared meaning, and the ordinary medicine of being known.',
          'You need both halves.',
          'And here is the difficult observation. The last generation\'s error was stigma — refusing the office and suffering in silence. This generation may be making the opposite error. We finally won the fight to get into the room, and then allowed the village to quietly disappear. We acquired therapy and assumed that was the entire job, while growing lonelier and lonelier outside of it. We traded one half of healing for the other.',
        ],
        pullQuote: 'Healing was never meant to be a solo project.',
      },
      {
        heading: 'What This Means in Practice',
        paragraphs: [
          'If therapy is helping you, continue working with your provider. At the same time, one professional relationship does not have to carry the entire weight of your healing. Where it is safe and appropriate, consider strengthening the other forms of support around you: trusted relationships, community, faith, chosen family, cultural connection, and spaces where you can be known beyond a clinical setting.',
          'If stigma is still keeping you from the door: consider this gentle permission. Your pain is real. Tending it is not weakness and it is not ingratitude — it may be among the most honoring things you ever do. Walk through the door. Then build your village on the other side of it.',
          'For many people, therapy can be strengthened by trusted relationships, community, faith, chosen family, and other forms of support. Because the reframe underneath all of this is simple: healing was never meant to be a solo project. Not in a room by yourself, and not inside your own head by yourself. Wholeness is communal. It always was.',
        ],
        pullQuote: null,
      },
      {
        heading: 'The Other Half',
        paragraphs: [
          'Return to that person in the chair — the one who did the brave thing and still felt the gap.',
          'The gap was never therapy failing them, and it was never them failing therapy. It was the missing half: the village the model never accounted for, and that modern life quietly took from all of us.',
          'Therapy is real. It is necessary. For some, it is the thing keeping them here, and nothing in this essay would take that away. But it was built to heal an individual — and you were never only an individual. You are a node in a web, made of your people, your faith, your history, and a whole world pressing in from outside.',
          'So healing the individual alone was never going to be the whole of it.',
          'Seek the professional support you need. And, where it is safe, build connection with people you trust. You were never meant to heal alone.',
        ],
        pullQuote: 'Find your village. That is the other half.',
        closingNote: 'This essay is part of Tamu Academy, an African-rooted learning platform exploring the mind, power, culture, public policy, economics, institutions, and the wider world. Watch the related episode through the [Tamu Academy Videos page](/videos).',
      },
    ],
    keyTakeaways: [
      'Therapy can provide trained, confidential, and individualized support, but wellbeing is also shaped by relationships, culture, spirituality, history, and social conditions.',
      'Distress should not automatically be treated as a purely private problem when structural pressures and community experiences also contribute to it.',
      'Professional care and safe community support do not have to compete; for many people, they can serve different and complementary roles.',
    ],
    reflectionQuestions: [
      'Which parts of your wellbeing feel individual, and which are connected to family, community, culture, faith, or social conditions?',
      'What forms of support can a trained professional provide that friends or family may not be able to provide?',
      'What safe relationships or communities help you feel known, supported, and connected outside of a clinical setting?',
    ],
    supportResources: {
      intro: 'Support is available. The appropriate resource depends on where you live and what kind of help you need.',
      emergencyNote: 'If you or another person is in immediate danger, contact the emergency services available in your location.',
      resources: [
        {
          label: 'Find A Helpline',
          description: 'A directory of verified crisis and emotional-support services in more than 175 countries.',
          url: 'https://findahelpline.com/',
          region: 'Global',
        },
        {
          label: '988 Suicide & Crisis Lifeline',
          description: 'Call or text 988, or use the official online chat, for free and confidential crisis support in the United States.',
          url: 'https://988lifeline.org/',
          phone: '988',
          region: 'United States',
        },
        {
          label: 'Mental 360',
          description: 'Mental 360 provides psychosocial support and lists a Kenyan national support helpline.',
          url: 'https://www.mental360.or.ke/',
          phone: '+254 710 360 360',
          region: 'Kenya',
        },
      ],
    },
    editorialNote: 'This essay discusses broad cultural and philosophical tendencies rather than every form of therapy or every African, immigrant, diaspora, or faith experience. Many therapists and therapeutic approaches explicitly address family systems, culture, spirituality, trauma, community, and structural conditions. Individual experiences with therapy and community support vary.',
    educationalNote: 'Tamu Academy content is provided for education and reflection. It is not medical advice and is not a substitute for professional mental-health care, diagnosis, treatment, or emergency support.',
    relatedResources: [],
    sources: [],
    previousArticle: 'the-real-cost-of-always-achieving',
    nextArticle: 'can-policy-make-us-happier',
    seoTitle: 'Why Therapy Alone Isn\'t Enough | Tamu Academy',
    seoDescription: 'Explore why therapy can be essential while community, belonging, culture, spirituality, and structural conditions also shape healing and wellbeing.',
  },
  {
    slug: 'can-policy-make-us-happier',
    title: 'Can Policy Make Us Happier?',
    subtitle: 'Governments are increasingly measuring wellbeing alongside economic performance. But what a state chooses to measure can reshape what it funds, rewards, and ultimately builds.',
    category: 'Power and Policy',
    status: 'in-development',
    summary: 'GDP can describe economic production without fully showing whether people are secure, connected, healthy, or able to flourish. This essay examines national wellbeing frameworks, income-and-happiness research, policy metrics, Ubuntu, and the difference between trying to manufacture happiness and protecting the conditions in which people can live well.',
    cardSummary: 'An examination of how public decisions influence the conditions that support security, belonging, opportunity, connection, and quality of life.',
    author: 'Tex Wambui',
    publisher: 'Tamu Academy',
    publicationDate: null,
    updatedDate: null,
    readingTime: 9,
    videoId: 'P9dXMOA9rO8',
    videoTitle: 'Can Policy Make Us Happier?',
    sections: [
      {
        heading: null,
        paragraphs: [
          'Around the world, governments have begun trying to measure wellbeing. Not only income. Not only the economy. Actual, felt, day-to-day quality of life. Some governments have created official wellbeing frameworks, national happiness surveys, wellbeing budgets, and ministerial roles focused on happiness or quality of life.',
          'On the surface, this sounds like unambiguous progress. Finally, a government that cares how you feel.',
          'Sit with it a moment longer, and it becomes stranger. A government. Measuring your happiness. Setting targets for it.',
          'Having spent a career inside the machinery of policy, I find the idea more unsettling than comforting — not because caring about people is wrong, but because I think the project is aimed at the wrong target. And aiming a government at the wrong target is how you build the wrong world.',
          'So the question worth asking is not the one in the title. It is the one underneath it: what happens to a whole society, depending on what it decides happiness even is?',
        ],
        pullQuote: null,
      },
      {
        heading: 'The Blind Spot in the Number We Already Use',
        paragraphs: [
          'The happiness movement began from a genuinely sound instinct.',
          'For most of modern history we have judged nations by one number above all others: GDP. It is an important measure of economic activity, but it was not designed to capture every dimension of welfare, distribution, health, belonging, environmental quality, or social connection. A country can grow richer every year while its people become lonelier, sicker, and more anxious. The number rises; the lives do not improve.',
          'What is less widely known is that Simon Kuznets, one of the principal architects of modern United States national-income accounting, warned against treating national income as a direct measure of national welfare. In his 1934 report to the United States Congress, he wrote that "the welfare of a nation can scarcely be inferred from a measure of national income."',
          'The warning was there from the beginning. We used the number that way regardless.',
        ],
        pullQuote: null,
      },
      {
        heading: 'The Countries That Tried Something Else',
        paragraphs: [
          'So some governments attempted an alternative.',
          'Bhutan developed Gross National Happiness as a multidimensional approach to national progress. Its index is commonly organized across nine domains and thirty-three indicators covering areas such as psychological wellbeing, health, education, time use, culture, governance, community vitality, ecology, and living standards. Bhutan\'s 2008 Constitution directs the state to promote conditions that support the pursuit of Gross National Happiness.',
          'In 2019, New Zealand delivered what its Treasury described as the country\'s first Wellbeing Budget. The budget used broader priorities covering mental health, child wellbeing, Māori and Pacific aspirations, productivity, and environmental transition. Funding proposals were required to include wellbeing analysis rather than relying only on conventional economic indicators. Scotland and Wales built frameworks of their own. For a moment, it appeared the world was turning a corner.',
          'The political durability of the branding proved limited. After a change of government, later budgets shifted priorities and no longer used the Wellbeing Budget label. That did not mean every wellbeing tool disappeared: New Zealand\'s Treasury continued to maintain its Living Standards Framework, wellbeing dashboard, and broader work on measuring living standards.',
          'The honest position, then, is this: the movement to measure wellbeing is real, it is serious, and in several places the political framing has shifted — while the underlying measurement work continues.',
        ],
        pullQuote: null,
      },
      {
        heading: 'A Metric Is a Steering Wheel',
        paragraphs: [
          'Why does any of this matter so much? Because of one thing that is obvious from inside government and nearly invisible from outside it.',
          'A metric is not a description. A metric is a steering wheel.',
          'From outside a system, measurements appear to describe reality — here is the unemployment rate, here is the test score, neutral as a thermometer. From inside, the opposite is true. Whatever you decide to measure becomes the thing everyone is judged against. And the moment people are judged against a number, they begin to chase it. Budgets bend toward it. Programmes are designed around it. Careers rise and fall on it. The metric ceases to describe the world and begins to bend it.',
          'When test scores dominate accountability systems, schools can face pressure to narrow instruction toward what is tested. When arrest counts become a dominant performance target, enforcement priorities can become distorted. This is not cynicism; it is simply what happens when a number becomes a target.',
          'So when a government announces it will measure happiness, that is not a soft, feel-good gesture. It is among the most consequential decisions a state can make — because that number will become a steering wheel, silently redirecting enormous sums and countless decisions toward producing more of whatever it counts as happiness.',
          'Which means everything depends on what, exactly, we are counting.',
        ],
        pullQuote: 'A metric is not a description. A metric is a steering wheel.',
      },
      {
        heading: 'What Fifty Years of Research Found',
        paragraphs: [
          'Here the story becomes genuinely fascinating, because the science of happiness has been arguing with itself for half a century.',
          'In 1974, economist Richard Easterlin identified a pattern that became known as the Easterlin paradox: although people with higher incomes within a society often report greater wellbeing, long-term economic growth does not always produce corresponding increases in average reported happiness. The interpretation and universality of this pattern have remained contested.',
          'In 2010, Daniel Kahneman and Angus Deaton analyzed survey responses from the United States and reported that emotional wellbeing rose with household income up to approximately $75,000 in 2008 dollars, after which the relationship flattened in their data. Their measure of life evaluation, however, continued to rise with income.',
          'Then in 2021, Matthew Killingsworth analyzed repeated real-time wellbeing reports from employed adults in the United States and found that both experienced wellbeing and life evaluation continued to rise with income across the range observed in the study, without the earlier $75,000 plateau. Two substantial findings, in apparent tension.',
          'What happened next is rare in science. Rather than feud, Kahneman and Killingsworth undertook an adversarial collaboration — working together specifically to reconcile their earlier results. In 2023, Kahneman, Killingsworth, and Barbara Mellers used this adversarial collaboration and found that higher income was associated with higher emotional wellbeing for most participants. Among the least-happy portion of the sample, however, the relationship appeared to flatten above a certain income range.',
          'The finding does not mean that income is irrelevant to people experiencing low wellbeing. It suggests more narrowly that additional income alone may have limited emotional benefits for some people once particular material thresholds have been reached.',
          'And an individual happiness score is blindest exactly where the need is greatest.',
        ],
        pullQuote: null,
      },
      {
        heading: 'The Lonely, Well-Served Individual',
        paragraphs: [
          'Now consider what happens when a government is pointed at that number.',
          'Many wellbeing systems combine subjective surveys with objective measures, but policymakers must still decide whether their frameworks adequately capture relationships, social trust, inequality, participation, and community connection.',
          'Optimize purely for individual satisfaction scores, and you will build a society extremely good at serving individuals — convenient, comfortable, personalized, frictionless. And you can accomplish all of it while the bonds between people quietly rot. You end up with a nation of well-served, comfortable, profoundly isolated people, each reasonably content, each alone. Everyone reports a solid seven out of ten, and something underneath it dies.',
          'Because the one thing an individual satisfaction score can struggle to see is us: the relationships, the web, the question of whether we still belong to one another.',
          'You can raise the number and lose the us.',
        ],
        pullQuote: 'You can raise the number and lose the us.',
      },
      {
        heading: 'Flourishing, Not Happiness',
        paragraphs: [
          'Perhaps, then, the problem is not the answer. Perhaps the problem is the question.',
          'There is an older question, one African thought has been asking for a very long time. It does not ask whether the individual is happy. It asks: is the community well? Can people meet their obligations to one another? Is anyone being abandoned?',
          'That is Ubuntu at the scale of a society. Ubuntu is used here as one relational philosophical lens rather than as a single definition shared identically across all African peoples or traditions. In this framing, wellbeing is not a private score carried inside you; it is relational. I am well when we are well. You cannot truly flourish while the people around you are falling apart, because you are made of those people.',
          'Point a government at that, and the choices change. Imagine two governments with identical budgets. The first aims at individual happiness: it spends on convenience, on personal services, on smoothing each separate life. Everyone becomes slightly more comfortable, alone. The second aims at collective flourishing: the same money goes toward what binds people — shared public space, support for families and elders, the connective tissue of a place.',
          'Same budget. Two entirely different societies. One produces comfortable, satisfied, lonely individuals. The other produces a people — connected, obligated to each other, and far more resilient when conditions worsen.',
          'Income and public spending can support the conditions around belonging, but money alone cannot guarantee meaningful relationships or community connection. That is precisely why the second government\'s choice of what to build and protect matters so much.',
        ],
        pullQuote: null,
      },
      {
        heading: 'Can Policy Make Us Happier?',
        paragraphs: [
          'So — can policy guarantee happiness? No. And this deserves saying plainly.',
          'Policy cannot manufacture or guarantee an individual\'s inner emotional state. Happiness lives in your relationships, your meaning, your inner life, the people you love. A government that promises to deliver happiness into you is overreaching — and a state confident it can engineer your inner feelings is one to regard with some suspicion.',
          'But that was always the wrong job. Here is the right one.',
          'Policy can help create or damage the social, economic, environmental, and institutional conditions in which people attempt to live well. Where you are not isolated. Where no one is abandoned. Where the bonds that actually make people well are protected rather than quietly eroded in the name of convenience.',
          'Stop asking policy to hand happiness to individuals. Start asking it to protect the conditions in which a community can flourish together.',
          'One is a vending machine. The other is a garden. A government cannot hand you the fruit — but it can absolutely tend the soil. Or poison it.',
        ],
        pullQuote: null,
      },
      {
        heading: 'What Is Actually Worth Measuring',
        paragraphs: [
          'Return to the image we began with: a government measuring your happiness, setting a target for how you feel.',
          'The discomfort was warranted. We were asking the state to hand us something it cannot give and should not attempt — to make us happy, one isolated individual at a time.',
          'But the question was never whether policy can make you happy.',
          'It is whether it lets us flourish.',
          'A government cannot give you a good life. But it can decide whether you have to live it alone. That — not the happiness number — is the thing worth measuring.',
        ],
        pullQuote: 'A government cannot give you a good life. But it can decide whether you have to live it alone.',
        closingNote: 'This essay is part of Tamu Academy, an African-rooted learning platform exploring the mind, power, culture, public policy, economics, institutions, and the wider world. Watch the related episode through the [Tamu Academy Videos page](/videos).',
      },
    ],
    keyTakeaways: [
      'GDP is an important measure of economic production, but it does not by itself describe every dimension of social welfare or human flourishing.',
      'Metrics shape institutional incentives, so policymakers must consider not only what a measure describes, but what behavior it may encourage.',
      'Policy cannot guarantee happiness, but it can strengthen or weaken the material, relational, environmental, and institutional conditions in which people live.',
    ],
    reflectionQuestions: [
      'Which dimensions of a good life are visible in economic measures, and which are more difficult to capture?',
      'What behaviors might institutions encourage when one measure becomes their dominant performance target?',
      'What should a government protect or provide if its goal is collective flourishing rather than the production of a single happiness score?',
    ],
    editorialNote: 'This essay presents a normative argument about public policy and wellbeing. Happiness, emotional wellbeing, life evaluation, flourishing, belonging, and social connection are related but distinct concepts. The cited studies do not establish that income or policy is irrelevant to wellbeing, and Ubuntu is presented as one relational lens rather than a universal African definition.',
    educationalNote: 'Tamu Academy content is provided for education, analysis, and reflection. It does not constitute governmental, financial, economic, medical, or mental-health advice.',
    relatedResources: [],
    sources: [
      { citation: 'Simon Kuznets, National Income, 1929–1932, NBER, 1934', url: 'https://www.nber.org/books-and-chapters/national-income-1929-1932' },
      { citation: 'GNH Centre Bhutan, What Is Gross National Happiness?', url: 'https://www.gnhcentrebhutan.org/what-is-gnh/' },
      { citation: 'New Zealand Treasury, The Wellbeing Budget 2019', url: 'https://www.treasury.govt.nz/publications/wellbeing-budget/wellbeing-budget-2019' },
      { citation: 'New Zealand Treasury, Living Standards Framework', url: 'https://www.treasury.govt.nz/information-and-services/nz-economy/higher-living-standards/our-living-standards-framework' },
      { citation: 'Richard Easterlin research overview — Happier Lives Institute', url: 'https://www.happierlivesinstitute.org/report/economic-growth/' },
      { citation: 'Kahneman and Deaton, High Income Improves Evaluation of Life but Not Emotional Well-Being, PNAS, 2010', url: 'https://www.pnas.org/doi/10.1073/pnas.1011492107' },
      { citation: 'Killingsworth, Experienced Well-Being Rises With Income, Even Above $75,000 Per Year, PNAS, 2021', url: 'https://www.pnas.org/doi/10.1073/pnas.2016976118' },
      { citation: 'Killingsworth, Kahneman, and Mellers, Income and Emotional Well-Being: A Conflict Resolved, PNAS, 2023', url: 'https://www.pnas.org/doi/10.1073/pnas.2208661120' },
    ],
    previousArticle: 'why-therapy-isnt-enough',
    nextArticle: 'who-controls-the-global-economy',
    seoTitle: 'Can Policy Make Us Happier? | Tamu Academy',
    seoDescription: 'Explore how GDP, wellbeing budgets, income research, policy metrics, and Ubuntu shape the debate over whether governments can support happiness and collective flourishing.',
  },
  {
    slug: 'who-controls-the-global-economy',
    title: 'Who Controls the Global Economy?',
    subtitle: null,
    category: 'Economics and Global Systems',
    status: 'in-development',
    summary: 'An introduction to the institutions, governments, corporations, and financial systems that influence how resources and economic power move across the world.',
    author: 'Tamu Academy',
    publicationDate: null,
    updatedDate: null,
    readingTime: null,
    videoId: 'Io9mZLfZ6yw',
    videoTitle: 'Who Controls the Global Economy?',
    sections: [],
    keyTakeaways: [],
    reflectionQuestions: [],
    relatedResources: [],
    sources: [],
    previousArticle: 'can-policy-make-us-happier',
    nextArticle: null,
    seoTitle: 'Who Controls the Global Economy? | Tamu Academy',
    seoDescription: 'A written companion to the Tamu Academy episode on global economic power, international institutions, and who makes the rules.',
  },
];

export function getArticleBySlug(slug) {
  return ARTICLES.find((a) => a.slug === slug) ?? null;
}